[package]
name = "four"
version = "0.1.0"
edition = "2024"

[dependencies]
exn = "0.3.1"
gpui = { git = "https://github.com/zed-industries/zed", rev = "38ca9106c5306ef93e52c35643df015a27f15b72" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "38ca9106c5306ef93e52c35643df015a27f15b72", features = ["font-kit", "wayland", "x11"] }
multiversion = "0.8.0"
