// This 16x16 baseline JPEG has red, green, blue, and white quadrants. Keeping it textual avoids a
// mysterious binary fixture while still exercising marker parsing, 4:2:0 sampling, and the IDCT.
const BASELINE_COLOR_JPEG_BASE64: &str = concat!(
    "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsK",
    "CwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQU",
    "FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAAQABADASIAAhEB",
    "AxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9",
    "AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6",
    "Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ip",
    "qrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEB",
    "AQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJB",
    "UQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RV",
    "VldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6",
    "wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD50r7Gr8vK",
    "/pbo8TPAz/Vz6n/wpe09p7T/AJdctuXk/wCnrve4vGHM/wDiNP1D3Pqn1T2vX2vP7X2flT5e",
    "X2fne/S2v//Z",
);

pub(crate) fn baseline_color_jpeg() -> Vec<u8> {
    decode_base64(BASELINE_COLOR_JPEG_BASE64)
}

pub(crate) fn progressive_color_jpeg() -> Vec<u8> {
    // Official libjpeg-turbo `testout_420_islow_prog.jpg` fixture.
    decode_base64(include_str!("../fixtures/progressive.txt"))
}

pub(crate) fn sequential_arithmetic_jpeg() -> Vec<u8> {
    // Official libjpeg-turbo `testimgari.jpg` interoperability fixture.
    decode_base64(include_str!("../fixtures/sequential_arithmetic.txt"))
}

pub(crate) fn progressive_arithmetic_jpeg() -> Vec<u8> {
    // Generated by libjpeg-turbo 3.2.0 from its official `testorig.ppm` fixture.
    decode_base64(include_str!("../fixtures/progressive_arithmetic.txt"))
}

pub(super) fn decode_base64(encoded: &str) -> Vec<u8> {
    assert_ne!(encoded, "");
    assert!(encoded.is_ascii());

    let compact: Vec<u8> = encoded
        .bytes()
        .filter(|byte| !byte.is_ascii_whitespace())
        .collect();
    let mut decoded = Vec::with_capacity(compact.len() / 4 * 3);
    let (groups, remainder) = compact.as_slice().as_chunks::<4>();
    assert_eq!(remainder.len(), 0);
    for group in groups {
        let first = u32::from(base64_value(group[0]));
        let second = u32::from(base64_value(group[1]));
        let third = u32::from(base64_value(group[2]));
        let fourth = u32::from(base64_value(group[3]));
        let bits = first << 18 | second << 12 | third << 6 | fourth;
        decoded.push(u8::try_from(bits >> 16).unwrap());
        if group[2] != b'=' {
            decoded.push(u8::try_from((bits >> 8) & 0xff).unwrap());
        }
        if group[3] != b'=' {
            decoded.push(u8::try_from(bits & 0xff).unwrap());
        }
    }
    assert_eq!(&decoded[..2], &[0xff, 0xd8]);
    assert_eq!(&decoded[decoded.len() - 2..], &[0xff, 0xd9]);
    decoded
}

fn base64_value(byte: u8) -> u8 {
    assert!(byte.is_ascii());
    assert_ne!(byte, b'\n');

    match byte {
        b'A'..=b'Z' => byte - b'A',
        b'a'..=b'z' => byte - b'a' + 26,
        b'0'..=b'9' => byte - b'0' + 52,
        b'+' => 62,
        b'/' => 63,
        b'=' => 0,
        _ => panic!("invalid base64 test fixture"),
    }
}
