[package]
name = "tonemapping"
version = "0.1.0"
edition = "2024"
description = "Tone-mapping operators for linear RGB colors"
publish = false

[dependencies]
multiversion = { workspace = true }

[dev-dependencies]
mimalloc = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "bulk"
harness = false
test = false
