[package]
name = "jpegxr"
version = "0.1.0"
edition = "2024"
description = "Pure Rust JPEG XR decoder"
license = "MIT"
publish = false

[dependencies]
rayon = { workspace = true }
thiserror = { workspace = true }
zerocopy = { workspace = true }
multiversion = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
mimalloc = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "decode"
harness = false
test = false

[[bench]]
name = "tile_merge"
harness = false
test = false
